server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由识别功能
      routes:
        - id: payment_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            - After=2020-05-28T21:30:38.836+08:00[Asia/Shanghai]
            # - Cookie=username,zzyy

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka #集群版