server:
  port: 9527
spring:
  application:
    name: cloud-gateway

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka #集群版